<?php
/**
 * VPI Dry Type product data.
 * Text taken verbatim from the live product pages.
 * Keyed by page slug.
 */
function getDryTypeProducts() {
    return [
        'distribution-transformers-dry-type' => [
            'name'  => 'Distribution Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-distribution.jpg',
            'icon'  => 'distribution.svg',
            'p1'    => 'VPI Dry Type Distribution Transformers are engineered for reliable power delivery in environments where safety, performance, and maintenance-free operation are crucial. These transformers utilize Vacuum Pressure Impregnation (VPI) technology, where windings are impregnated with high-grade varnish under vacuum, ensuring superior insulation, mechanical strength, and heat dissipation.',
            'p2'    => 'Designed for use in commercial complexes, hospitals, educational institutions, industries, and residential networks, these transformers eliminate the need for oil-based cooling, providing an environmentally friendly and fire-safe power solution with exceptional operational efficiency.',
            'features' => [
                'Rated up to 33 kV for indoor and outdoor applications.',
                'Fire-resistant and self-extinguishing insulation system.',
                'Excellent thermal performance with natural air cooling.',
                'Maintenance-free operation with no risk of oil leakage.',
                'Low noise levels for installation in populated areas.',
                'Compact and lightweight design for easy handling.',
                'Resistant to moisture, dust, and contaminants.',
                'High short-circuit withstand capacity.',
                'Long service life with minimal operational costs.',
                'Compliant with IS/IEC international performance standards.',
            ],
        ],

        'power-transformer-dry-type' => [
            'name'  => 'Power Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-power.jpg',
            'icon'  => 'power.svg',
            'p1'    => 'VPI Dry Type Power Transformers are built to perform under demanding load and environmental conditions. They provide efficient voltage transformation for medium-voltage networks, ensuring operational safety and energy efficiency. With vacuum pressure impregnated windings and resin-coated insulation, these transformers offer excellent resistance to humidity, chemical contaminants, and thermal stress.',
            'p2'    => 'Ideal for industrial plants, substations, renewable energy stations, and utility applications, they provide stable power delivery without the risk of oil leaks or fire hazards, making them suitable for confined or public environments.',
            'features' => [
                'Voltage class up to 33 kV.',
                'Highly durable VPI insulation for superior protection.',
                'Excellent overload capability.',
                'Low partial discharge and minimal power loss.',
                'No oil usage — completely fire and spill proof.',
                'Air-cooled design ensures safe indoor operation.',
                'Easy to install and relocate.',
                'High mechanical and thermal endurance.',
                'Suitable for both step-up and step-down applications.',
                'Designed as per IS, IEC, and ANSI standards.',
            ],
        ],

        'inverter-duty-transformer-dry-type' => [
            'name'  => 'Inverter Duty Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-inverter.jpg',
            'icon'  => 'inverter.svg',
            'p1'    => 'These transformers are designed to integrate seamlessly with inverter-based power systems. Their VPI windings provide excellent insulation against high-frequency harmonics, voltage surges, and thermal stress, ensuring steady performance in renewable and industrial power conversion setups.',
            'p2'    => 'They are widely used in solar, wind, UPS, and variable frequency drive (VFD) applications, where reliability, low loss, and harmonic mitigation are critical. Their air-cooled construction allows safe indoor installation without compromising performance.',
            'features' => [
                'Designed for inverter-based and VFD systems.',
                'Handles non-linear and fluctuating loads efficiently.',
                'Superior harmonic resistance and insulation quality.',
                'No oil or fire hazard.',
                'Compact and lightweight construction.',
                'High dielectric strength for surge protection.',
                'Efficient cooling through Air Natural (AN) system.',
                'Long operational life under variable frequency loads.',
                'Reduced electromagnetic interference (EMI).',
                'Customizable voltage ratios for different inverter systems.',
            ],
        ],

        'converter-duty-transformer-dry-type' => [
            'name'  => 'Converter Duty Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-converter.jpg',
            'icon'  => 'converter.svg',
            'p1'    => 'VPI Dry Type Converter Duty Transformers are built to handle complex power conversion processes in drives, converters, and rectifier systems. They ensure consistent voltage regulation, minimal distortion, and high operational efficiency even under non-linear loading conditions.',
            'p2'    => 'The VPI insulation system ensures high dielectric strength, mechanical rigidity, and excellent heat dissipation — ideal for heavy industrial and continuous-duty operations.',
            'features' => [
                'Optimized for AC/DC converter applications.',
                'High short-circuit and overload capability.',
                'Low noise and vibration levels.',
                'Air-cooled and fire-safe design.',
                'Harmonic distortion suppression.',
                'Long operational life with minimal upkeep.',
                'High mechanical and dielectric strength.',
                'Compact, lightweight construction.',
                'Suitable for variable load applications.',
                'Meets IEC and IS manufacturing standards.',
            ],
        ],

        'furnace-duty-transformer-dry-type' => [
            'name'  => 'Furnace Duty Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-furnace.jpg',
            'icon'  => 'furnace.svg',
            'p1'    => 'VPI Dry Type Furnace Duty Transformers are engineered for demanding furnace applications such as electric arc, induction, and ladle furnaces, where heat, short-circuit stress, and fluctuating loads are constant challenges. With high mechanical strength and advanced resin-impregnated insulation, these transformers deliver exceptional reliability and voltage stability under cyclic operations.',
            'p2'    => 'Their oil-free, air-cooled construction ensures operational safety and eliminates fire hazards, making them a perfect solution for steel, foundry, and alloy manufacturing units. The superior thermal management enables uninterrupted performance even under extreme operating temperatures.',
            'features' => [
                'Designed for high inrush and short-circuit current conditions.',
                'Excellent thermal endurance under heavy-duty cycles.',
                'Resin-impregnated coils provide superior insulation.',
                'Fire-resistant and safe for confined installations.',
                'Minimal maintenance and downtime.',
                'Stable voltage output during fluctuating furnace loads.',
                'Compact and robust design with high mechanical strength.',
                'Reduced noise and vibration during operation.',
                'Environmentally friendly — no oil leakage.',
                'Proven performance in continuous industrial applications.',
            ],
        ],

        'lightning-transformer-dry-type' => [
            'name'  => 'Lightning Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-lightning.jpg',
            'icon'  => 'lightning.svg',
            'p1'    => 'VPI Dry Type Lightning Transformers protect electrical systems from high-voltage surges caused by lightning strikes and switching transients. They act as surge buffers, ensuring critical equipment and circuits remain unaffected by sudden overvoltage conditions.',
            'p2'    => 'With advanced resin insulation and fast response characteristics, these transformers ensure reliable protection and voltage regulation. Their oil-free construction and robust design make them ideal for both indoor and outdoor surge-protection applications.',
            'features' => [
                'Provides high-level protection from lightning and surges.',
                'VPI insulation ensures quick surge absorption.',
                'Reliable performance under transient voltage conditions.',
                'Zero fire risk and no oil contamination.',
                'Long operational lifespan in harsh conditions.',
                'Compatible with industrial and utility networks.',
                'Compact design for easy panel or substation integration.',
                'Low maintenance and high dielectric strength.',
                'Tested to IEC surge withstand standards.',
                'Stable operation ensures extended equipment protection.',
            ],
        ],

        'isolation-transformer-dry-type' => [
            'name'  => 'Isolation Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-isolation.jpg',
            'icon'  => 'isolation.svg',
            'p1'    => 'VPI Dry Type Isolation Transformers are designed to electrically isolate sensitive equipment from the primary power source, eliminating noise, harmonics, and voltage spikes. The vacuum pressure impregnation process enhances dielectric strength, ensuring clean and stable power delivery.',
            'p2'    => 'These transformers are widely used in medical facilities, data centers, laboratories, and control systems, where safety, performance, and uninterrupted operation are paramount. Their dry construction ensures complete fire safety and ease of maintenance.',
            'features' => [
                'Complete electrical isolation between input and output circuits.',
                'High noise and harmonic suppression capability.',
                'Excellent insulation through resin-impregnated windings.',
                'Fire-safe, oil-free construction for indoor environments.',
                'Stable voltage and consistent power quality.',
                'Compact design suitable for confined spaces.',
                'Energy-efficient with low load losses.',
                'Easy installation and low maintenance.',
                'Extended service life under continuous duty.',
                'Ideal for precision electronic and medical systems.',
            ],
        ],

        'generator-transformer-dry-type' => [
            'name'  => 'Generator Transformers',
            'range' => 'Upto 5 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'dry-generator.jpg',
            'icon'  => 'generator.svg',
            'p1'    => 'VPI Dry Type Generator Transformers are designed to connect generators to the electrical grid or plant distribution systems, efficiently stepping up or down the voltage as required. The VPI process ensures superior insulation, making these transformers ideal for high-current, high-temperature environments.',
            'p2'    => 'With their air-cooled, fire-safe design, they are suitable for power plants, renewable energy stations, and backup generator systems where oil-filled transformers pose a safety concern. They combine long-term reliability with low maintenance costs.',
            'features' => [
                'Voltage range up to 33 kV.',
                'Superior insulation via vacuum pressure impregnation.',
                'Withstands voltage surges and thermal cycling.',
                'No oil usage — completely fire and spill proof.',
                'Compact design suitable for confined generator rooms.',
                'Excellent cooling with natural air flow.',
                'High mechanical strength and vibration resistance.',
                'Low operational losses and high efficiency.',
                'Ideal for indoor power generation setups.',
                'Long operational life with minimal servicing.',
            ],
        ],
    ];
}
