<?php
/**
 * Oil Filled product data.
 * Text taken verbatim from the live product detail pages.
 * Keyed by page slug.
 */
function getOilFilledProducts() {
    return [
        'distribution-transformers-oil-filled' => [
            'name'  => 'Distribution Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-distribution.jpg',
            'icon'  => 'distribution.svg',
            'p1'    => 'Distribution transformers are designed to deliver reliable power supply across industrial, commercial, and utility networks by efficiently stepping down high-voltage electricity to usable levels. Built with precision-engineered components and advanced insulation systems, these transformers ensure minimal energy loss during transmission and consistent voltage regulation even under fluctuating load conditions.',
            'p2'    => 'Engineered for durability and optimal thermal performance, these oil-filled transformers are ideal for both indoor and outdoor installations. Their robust construction, high-quality materials, and superior cooling systems guarantee long operational life, safety, and low maintenance — making them a dependable backbone for everyday power distribution.',
            'features' => [
                'Rated capacity up to 20 MVA for diverse load requirements.',
                'Advanced core design minimizes no-load losses.',
                'High-grade insulating oil ensures efficient heat dissipation.',
                'Hermetically sealed tank for protection against moisture.',
                'Copper windings for high conductivity and energy efficiency.',
                'Low noise operation through precision core lamination.',
                'Rugged construction suitable for outdoor environments.',
                'Efficient tap changers for voltage regulation.',
                'Tested to international performance standards (IS/IEC).',
                'Long service life with minimal maintenance requirements.',
            ],
            'gallery' => ['oil-distribution-1.jpg'],
        ],

        'power-transformers-oil-filled' => [
            'name'  => 'Power Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-power.jpg',
            'icon'  => 'power.svg',
            'p1'    => 'Power transformers play a crucial role in electrical power systems, managing high-voltage transmission efficiently between generating stations and distribution networks. Designed for superior performance and reliability, these oil-filled transformers ensure maximum power transfer with minimum loss, meeting the needs of utilities and large-scale industrial operations.',
            'p2'    => 'Each unit is manufactured with advanced core materials and high-grade conductors to enhance energy efficiency and reliability. Their oil-cooled, conservator-type construction ensures excellent thermal management, while built-in protection mechanisms safeguard against voltage surges and thermal stress.',
            'features' => [
                'Voltage rating up to 33 kV for heavy-duty industrial applications.',
                'High short-circuit withstand capacity.',
                'Low-loss core design improves efficiency.',
                'On-load tap changer for stable voltage control.',
                'Enhanced insulation for long operational life.',
                'Efficient oil circulation for better cooling.',
                'Compact and space-efficient design.',
                'Vibration-free operation with low noise levels.',
                'Compliance with IS, IEC, and ANSI standards.',
                'Suitable for both step-up and step-down configurations.',
            ],
            'gallery' => ['oil-power-1.jpg', 'oil-power-2.jpg'],
        ],

        'inverter-duty-transformers-oil-filled' => [
            'name'  => 'Inverter Duty Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-inverter.jpg',
            'icon'  => 'inverter.svg',
            'p1'    => 'Inverter duty transformers are engineered to connect inverter systems with the power grid or local loads, ensuring smooth power conversion and reliable energy flow. They are optimized to handle the harmonics and voltage fluctuations typical of inverter-based systems, commonly used in solar and wind energy setups.',
            'p2'    => 'These transformers feature enhanced insulation, robust winding designs, and superior thermal management to ensure long-term stability under dynamic inverter load conditions. Their design ensures efficient DC-to-AC power transformation while minimizing losses and electromagnetic interference.',
            'features' => [
                'Designed specifically for inverter-based applications.',
                'Handles non-linear loads with low harmonic distortion.',
                'Excellent dielectric strength for voltage transients.',
                'Robust copper windings for enhanced conductivity.',
                'Optimized cooling system for extended lifespan.',
                'Compact footprint suitable for solar farms and industrial setups.',
                'Supports both grid-tied and off-grid operations.',
                'High short-circuit strength and overload capacity.',
                'Reduced maintenance with superior oil filtration.',
                'Proven reliability in renewable energy environments.',
            ],
            'gallery' => ['oil-inverter-1.jpg'],
        ],

        'converter-duty-transformers-oil-filled' => [
            'name'  => 'Converter Duty Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-converter.jpg',
            'icon'  => 'converter.svg',
            'p1'    => 'Converter duty transformers are essential in rectifier and converter systems, supporting power conversion between AC and DC for applications like electrolysis, drives, and traction systems. They are engineered to handle large current variations and harmonic distortions while maintaining voltage stability.',
            'p2'    => 'The transformers use reinforced insulation, customized vector groups, and advanced cooling systems to ensure continuous and efficient operation under dynamic loads. Their high reliability and durability make them ideal for industrial converters and heavy-duty equipment.',
            'features' => [
                'Custom-designed for converter and rectifier systems.',
                'Handles high harmonic content effectively.',
                'Reinforced insulation for electrical strength.',
                'High overload capacity for fluctuating loads.',
                'Efficient cooling system prevents overheating.',
                'Suitable for AC/DC conversion in heavy industries.',
                'Compact and durable construction.',
                'Easy integration into control systems.',
                'Long operational life and low failure rate.',
                'Designed for continuous 24x7 operation.',
            ],
            'gallery' => ['oil-converter-1.jpg', 'oil-converter-2.jpg'],
        ],

        'furnace-duty-transformers-oil-filled' => [
            'name'  => 'Furnace Duty Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-furnace.jpg',
            'icon'  => 'furnace.svg',
            'p1'    => 'Furnace duty transformers are specially engineered to meet the demanding conditions of electric arc furnaces, induction furnaces, and ladle furnaces used in steel and metal processing industries. These transformers are designed to handle extreme short-circuit currents, rapid load fluctuations, and high thermal stresses without performance degradation.',
            'p2'    => 'Their oil-filled construction ensures excellent heat dissipation and stable voltage regulation even under cyclic and fluctuating loads. Built with superior-grade materials and robust insulation systems, they guarantee efficient power delivery, long service life, and operational safety in high-temperature industrial environments.',
            'features' => [
                'Designed for heavy-duty furnace applications.',
                'Withstands extreme short-circuit and overload conditions.',
                'Excellent voltage regulation for arc stability.',
                'High thermal endurance for cyclic load operations.',
                'Low noise and vibration levels.',
                'Superior cooling system ensures temperature control.',
                'Customized secondary voltage ranges as per furnace type.',
                'High mechanical strength and durable tank design.',
                'Efficient oil circulation for uniform cooling.',
                'Proven performance in continuous industrial operations.',
            ],
            'gallery' => ['oil-furnace-1.jpg', 'oil-furnace-2.jpg'],
        ],

        'rectifier-transformers-oil-filled' => [
            'name'  => 'Rectifier Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-rectifier.jpg',
            'icon'  => 'rectifier.svg',
            'p1'    => 'Rectifier transformers are built to supply controlled DC power by converting AC input to DC output through rectifier circuits. They are vital in electrochemical processes, DC traction systems, and industrial power supplies requiring precise voltage control and smooth DC output.',
            'p2'    => 'Designed with reinforced insulation and harmonic-resistant cores, these oil-filled transformers ensure high efficiency, low waveform distortion, and stable performance under varying load conditions. Their durable design guarantees long-term reliability in high-current industrial environments.',
            'features' => [
                'Optimized for AC to DC conversion.',
                'Handles high harmonic content effectively.',
                'Robust insulation system for voltage stability.',
                'High efficiency and low losses.',
                'Customized vector groups for different rectifier configurations.',
                'Compact design with efficient oil cooling.',
                'High overload and thermal capacity.',
                'Suitable for electrolysis, plating, and traction systems.',
                'Minimal noise and vibration during operation.',
                'Long operational life with low maintenance needs.',
            ],
            'gallery' => ['oil-rectifier-1.jpg'],
        ],

        'isolation-transformers-oil-filled' => [
            'name'  => 'Isolation Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-isolation.jpg',
            'icon'  => 'isolation.svg',
            'p1'    => 'Isolation transformers are used to electrically isolate equipment from the power source, providing safety, noise reduction, and protection from electrical disturbances. These transformers ensure the load receives a clean and stable power supply without direct electrical connection to the main circuit.',
            'p2'    => 'They are particularly suitable for sensitive equipment, medical installations, and control systems that require protection from power spikes, surges, and harmonics. Built with high dielectric strength and oil-filled insulation, they ensure long-term stability and reliability.',
            'features' => [
                'Provides complete electrical isolation between circuits.',
                'Eliminates noise, spikes, and transients.',
                'Enhances equipment safety and longevity.',
                'Low leakage current and high insulation resistance.',
                'Oil-filled for excellent cooling and performance.',
                'Designed for industrial and medical applications.',
                'Compact design suitable for indoor installations.',
                'Minimizes electromagnetic interference (EMI).',
                'High efficiency and voltage stability.',
                'Long operational life with low maintenance.',
            ],
            'gallery' => ['oil-isolation-1.jpg'],
        ],

        'lightning-transformers-oil-filled' => [
            'name'  => 'Lightning Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-lightning.jpg',
            'icon'  => 'lightning.svg',
            'p1'    => 'Lightning transformers are designed to protect electrical systems and equipment from lightning-induced voltage surges and transient overvoltages. These transformers act as a buffer, limiting the surge impact and ensuring stable operation of connected devices.',
            'p2'    => 'With high insulation strength and specialized surge-absorbing design, they are crucial in areas prone to lightning activity or voltage fluctuations. Their oil-filled construction ensures reliability, fast response time, and extended service life under harsh environmental conditions.',
            'features' => [
                'Provides effective protection against lightning surges.',
                'High dielectric strength to absorb transient voltages.',
                'Fast response to overvoltage conditions.',
                'Oil-filled for superior insulation and cooling.',
                'Compact and rugged construction for outdoor use.',
                'Compatible with various voltage systems.',
                'Reduces downtime and equipment damage.',
                'Ensures stable operation during electrical disturbances.',
                'Low maintenance and long operational lifespan.',
                'Proven reliability in high-risk lightning zones.',
            ],
            'gallery' => ['oil-lightning-1.jpg', 'oil-lightning-2.jpg'],
        ],

        'generator-transformers-oil-filled' => [
            'name'  => 'Generator Transformers',
            'range' => 'Upto 20 MVA',
            'volt'  => 'Upto 33KV',
            'image' => 'oil-generator.jpg',
            'icon'  => 'generator.svg',
            'p1'    => 'Generator transformers are used to step up the voltage generated by power plants to transmission levels for efficient long-distance power transfer. They play a vital role in linking generators to the power grid, ensuring efficient energy transfer, stability, and minimal loss.',
            'p2'    => 'Designed for high performance and durability, these oil-filled transformers offer superior thermal and electrical characteristics. Their robust construction, advanced insulation system, and excellent cooling ensure continuous operation under heavy load and dynamic grid conditions.',
            'features' => [
                'Connects generators to high-voltage transmission lines.',
                'Handles high current and voltage fluctuations efficiently.',
                'Low loss core design ensures maximum efficiency.',
                'Designed for continuous operation under heavy load.',
                'Superior insulation withstands thermal and electrical stress.',
                'Oil-cooled system for effective heat dissipation.',
                'Rugged design suitable for power plant environments.',
                'Compatible with various generator types and ratings.',
                'Compliant with global electrical standards (IS/IEC).',
                'Extended operational life with minimal service needs.',
            ],
            'gallery' => ['oil-generator-1.jpg'],
        ],
    ];
}
